config/routes.rb
Rails.application.routes.draw do
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:sucess] = "Profile created"
      redirect_to @kitten
    else
      flash[:danger] = "Wrong info"
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Profile updated"
      redirect_to @kitten
    else
      flash[:danger] = "Wrong info"
      render 'edit'
    end
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = "Kitten exterminated"
    redirect_to kittens_url
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @kitten }
    end
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3 class="text-center">Edit profile</h3>
    <%= form_for(@kitten) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :age %>
        <%= f.number_field :age, in: 0..50, step:1, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :cuteness %>
        <%= f.number_field :cuteness, in: 0..10, step:1, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :softness %>
        <%= f.number_field :softness, in: 0..10, step:1, class: 'form-control' %>
      </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
  <%= link_to "Exterminate kitten", @kitten, class: "btn btn-default", method: :delete %>
</div>

app/views/kittens/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3 class="text-center">Kittens Paradise</h3>
    <% @kittens.each do |kitten| %>
      <div style="margin: 20px 0px">
        <div class="row">
          <div class="col-md-8">
            <h4><%= kitten.name %></h4>
          </div>
          <div class="col-md-4 text-right">
            <%= link_to "Exterminate kitten", kitten, class: "btn btn-default text-right", method: :delete %>
          </div>
        </div>
        <ul class="text-center list-group">
          <li class="list-group-item">Age: <%= kitten.age %></li>
          <li class="list-group-item">Cuteness: <%= kitten.cuteness %></li>
          <li class="list-group-item">Softness <%= kitten.softness %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/kittens/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h3 class="text-center">Create a profile for your kitten!</h3>
    <%= form_for(@kitten) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :age %>
        <%= f.number_field :age, in: 0..50, step:1, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :cuteness %>
        <%= f.number_field :cuteness, in: 0..10, step:1, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :softness %>
        <%= f.number_field :softness, in: 0..10, step:1, class: 'form-control' %>
      </div>
        <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/kittens/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <h4><%= @kitten.name %></h4>
      <ul class="list-group">
        <li class="list-group-item">Age: <%= @kitten.age %></li>
        <li class="list-group-item">Cuteness: <%= @kitten.cuteness %></li>
        <li class="list-group-item">Softness <%= @kitten.softness %></li>
      </ul>
  </div>
  <%= link_to "Exterminate kitten", @kitten, class: "btn btn-default text-right", method: :delete %>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "Kittens App", kittens_path, class: "navbar-brand" %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittensApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>


      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>